### ISSUE TITLE
add cpphs to build-depends?

### ISSUE THREAD

**Issue by cartazio** [agrafix/openai-hs#20]
tehres a cabal field for build tool deps, then it wouldn't fail for users who dont have cpphs installed...

**Comment by cartazio** [comment]
https://cabal.readthedocs.io/en/stable/cabal-package.html#pkg-field-build-tool-depends

**Comment by nickhs** [comment]
Hi @cartazio if you wouldn't mind taking a peek at the linked PR and offering feedback otherwise I'll merge it in a week or so

**Comment by cartazio** [comment]
Looks plausible to me :)
